export const ADD_BILL = "ADD_BILL"
export const DELETE_BILL = "DELETE_BILL"

export const SET_PAYMENT_METHOD_RANGE = "SET_PAYMENT_METHOD_RANGE"
export const SET_EXPENSES_RANGE = "SET_EXPENSES_RANGE"
export const SET_SHOPPINGTYPE_RANGE = "SET_SHOPPINGTYPE_RANGE"

export const LOGGED_IN = "LOGGED_IN"
export const LOGGED_OUT = "LOGGED_OUT"

